### ISSUE TITLE
Replace 0px with 0 not working properly

### ISSUE THREAD

**Issue by codesbiome** [codesbiome/csspress#1]
When a property has multi values, 0px isn't being replaced correctly

**Attempted:**
```css
body {
    padding: 15px 20px 15px 20px;
    margin: 20px 0px;  /* 0px should be 0 only */
}
```

**Output:**
```css
body {
    padding: 15px 20px;
    margin: 20px 0px;
}
```

**Expected:**
```css
body {
    padding: 15px 20px;
    margin: 20px 0;
}
```
